// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: normal_upload.proto

package apiconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	api "github.com/phalanx-labs/beacon-bucket-sdk/internal/api"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// NormalUploadServiceName is the fully-qualified name of the NormalUploadService service.
	NormalUploadServiceName = "proto.NormalUploadService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// NormalUploadServiceUploadProcedure is the fully-qualified name of the NormalUploadService's
	// Upload RPC.
	NormalUploadServiceUploadProcedure = "/proto.NormalUploadService/Upload"
	// NormalUploadServiceCacheVerifyProcedure is the fully-qualified name of the NormalUploadService's
	// CacheVerify RPC.
	NormalUploadServiceCacheVerifyProcedure = "/proto.NormalUploadService/CacheVerify"
	// NormalUploadServiceDeleteProcedure is the fully-qualified name of the NormalUploadService's
	// Delete RPC.
	NormalUploadServiceDeleteProcedure = "/proto.NormalUploadService/Delete"
)

// NormalUploadServiceClient is a client for the proto.NormalUploadService service.
type NormalUploadServiceClient interface {
	Upload(context.Context, *connect.Request[api.UploadRequest]) (*connect.Response[api.UploadResponse], error)
	CacheVerify(context.Context, *connect.Request[api.CacheVerifyRequest]) (*connect.Response[api.CacheVerifyResponse], error)
	Delete(context.Context, *connect.Request[api.DeleteRequest]) (*connect.Response[api.DeleteResponse], error)
}

// NewNormalUploadServiceClient constructs a client for the proto.NormalUploadService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewNormalUploadServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) NormalUploadServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	normalUploadServiceMethods := api.File_normal_upload_proto.Services().ByName("NormalUploadService").Methods()
	return &normalUploadServiceClient{
		upload: connect.NewClient[api.UploadRequest, api.UploadResponse](
			httpClient,
			baseURL+NormalUploadServiceUploadProcedure,
			connect.WithSchema(normalUploadServiceMethods.ByName("Upload")),
			connect.WithClientOptions(opts...),
		),
		cacheVerify: connect.NewClient[api.CacheVerifyRequest, api.CacheVerifyResponse](
			httpClient,
			baseURL+NormalUploadServiceCacheVerifyProcedure,
			connect.WithSchema(normalUploadServiceMethods.ByName("CacheVerify")),
			connect.WithClientOptions(opts...),
		),
		delete: connect.NewClient[api.DeleteRequest, api.DeleteResponse](
			httpClient,
			baseURL+NormalUploadServiceDeleteProcedure,
			connect.WithSchema(normalUploadServiceMethods.ByName("Delete")),
			connect.WithClientOptions(opts...),
		),
	}
}

// normalUploadServiceClient implements NormalUploadServiceClient.
type normalUploadServiceClient struct {
	upload      *connect.Client[api.UploadRequest, api.UploadResponse]
	cacheVerify *connect.Client[api.CacheVerifyRequest, api.CacheVerifyResponse]
	delete      *connect.Client[api.DeleteRequest, api.DeleteResponse]
}

// Upload calls proto.NormalUploadService.Upload.
func (c *normalUploadServiceClient) Upload(ctx context.Context, req *connect.Request[api.UploadRequest]) (*connect.Response[api.UploadResponse], error) {
	return c.upload.CallUnary(ctx, req)
}

// CacheVerify calls proto.NormalUploadService.CacheVerify.
func (c *normalUploadServiceClient) CacheVerify(ctx context.Context, req *connect.Request[api.CacheVerifyRequest]) (*connect.Response[api.CacheVerifyResponse], error) {
	return c.cacheVerify.CallUnary(ctx, req)
}

// Delete calls proto.NormalUploadService.Delete.
func (c *normalUploadServiceClient) Delete(ctx context.Context, req *connect.Request[api.DeleteRequest]) (*connect.Response[api.DeleteResponse], error) {
	return c.delete.CallUnary(ctx, req)
}

// NormalUploadServiceHandler is an implementation of the proto.NormalUploadService service.
type NormalUploadServiceHandler interface {
	Upload(context.Context, *connect.Request[api.UploadRequest]) (*connect.Response[api.UploadResponse], error)
	CacheVerify(context.Context, *connect.Request[api.CacheVerifyRequest]) (*connect.Response[api.CacheVerifyResponse], error)
	Delete(context.Context, *connect.Request[api.DeleteRequest]) (*connect.Response[api.DeleteResponse], error)
}

// NewNormalUploadServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewNormalUploadServiceHandler(svc NormalUploadServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	normalUploadServiceMethods := api.File_normal_upload_proto.Services().ByName("NormalUploadService").Methods()
	normalUploadServiceUploadHandler := connect.NewUnaryHandler(
		NormalUploadServiceUploadProcedure,
		svc.Upload,
		connect.WithSchema(normalUploadServiceMethods.ByName("Upload")),
		connect.WithHandlerOptions(opts...),
	)
	normalUploadServiceCacheVerifyHandler := connect.NewUnaryHandler(
		NormalUploadServiceCacheVerifyProcedure,
		svc.CacheVerify,
		connect.WithSchema(normalUploadServiceMethods.ByName("CacheVerify")),
		connect.WithHandlerOptions(opts...),
	)
	normalUploadServiceDeleteHandler := connect.NewUnaryHandler(
		NormalUploadServiceDeleteProcedure,
		svc.Delete,
		connect.WithSchema(normalUploadServiceMethods.ByName("Delete")),
		connect.WithHandlerOptions(opts...),
	)
	return "/proto.NormalUploadService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case NormalUploadServiceUploadProcedure:
			normalUploadServiceUploadHandler.ServeHTTP(w, r)
		case NormalUploadServiceCacheVerifyProcedure:
			normalUploadServiceCacheVerifyHandler.ServeHTTP(w, r)
		case NormalUploadServiceDeleteProcedure:
			normalUploadServiceDeleteHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedNormalUploadServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedNormalUploadServiceHandler struct{}

func (UnimplementedNormalUploadServiceHandler) Upload(context.Context, *connect.Request[api.UploadRequest]) (*connect.Response[api.UploadResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("proto.NormalUploadService.Upload is not implemented"))
}

func (UnimplementedNormalUploadServiceHandler) CacheVerify(context.Context, *connect.Request[api.CacheVerifyRequest]) (*connect.Response[api.CacheVerifyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("proto.NormalUploadService.CacheVerify is not implemented"))
}

func (UnimplementedNormalUploadServiceHandler) Delete(context.Context, *connect.Request[api.DeleteRequest]) (*connect.Response[api.DeleteResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("proto.NormalUploadService.Delete is not implemented"))
}
