// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: normal_upload.proto

package bGrpcApi

import (
	generate "github.com/bamboo-services/bamboo-base-go/grpc/generate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BucketId      string                 `protobuf:"bytes,1,opt,name=bucket_id,json=bucketId,proto3" json:"bucket_id,omitempty"`
	PathId        string                 `protobuf:"bytes,2,opt,name=path_id,json=pathId,proto3" json:"path_id,omitempty"`
	ContentBase64 string                 `protobuf:"bytes,3,opt,name=content_base64,json=contentBase64,proto3" json:"content_base64,omitempty"` // 必须为 MIME Base64 格式（如 data:image/png;base64,...）
	Description   *string                `protobuf:"bytes,4,opt,name=description,proto3,oneof" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadRequest) Reset() {
	*x = UploadRequest{}
	mi := &file_normal_upload_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadRequest) ProtoMessage() {}

func (x *UploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_normal_upload_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadRequest.ProtoReflect.Descriptor instead.
func (*UploadRequest) Descriptor() ([]byte, []int) {
	return file_normal_upload_proto_rawDescGZIP(), []int{0}
}

func (x *UploadRequest) GetBucketId() string {
	if x != nil {
		return x.BucketId
	}
	return ""
}

func (x *UploadRequest) GetPathId() string {
	if x != nil {
		return x.PathId
	}
	return ""
}

func (x *UploadRequest) GetContentBase64() string {
	if x != nil {
		return x.ContentBase64
	}
	return ""
}

func (x *UploadRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

type UploadResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	BaseResponse          *generate.BaseResponse `protobuf:"bytes,1,opt,name=base_response,json=baseResponse,proto3" json:"base_response,omitempty"`
	FileId                string                 `protobuf:"bytes,2,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	BucketId              string                 `protobuf:"bytes,3,opt,name=bucket_id,json=bucketId,proto3" json:"bucket_id,omitempty"`
	PathId                string                 `protobuf:"bytes,4,opt,name=path_id,json=pathId,proto3" json:"path_id,omitempty"`
	FileName              string                 `protobuf:"bytes,5,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	Size                  int64                  `protobuf:"varint,6,opt,name=size,proto3" json:"size,omitempty"`
	Etag                  *string                `protobuf:"bytes,7,opt,name=etag,proto3,oneof" json:"etag,omitempty"`
	MimeType              string                 `protobuf:"bytes,8,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	IsCache               bool                   `protobuf:"varint,9,opt,name=is_cache,json=isCache,proto3" json:"is_cache,omitempty"`
	UploadedAt            *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=uploaded_at,json=uploadedAt,proto3" json:"uploaded_at,omitempty"`
	CacheVerifyDeadlineAt *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=cache_verify_deadline_at,json=cacheVerifyDeadlineAt,proto3,oneof" json:"cache_verify_deadline_at,omitempty"`
	ObjectKey             *string                `protobuf:"bytes,12,opt,name=object_key,json=objectKey,proto3,oneof" json:"object_key,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *UploadResponse) Reset() {
	*x = UploadResponse{}
	mi := &file_normal_upload_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadResponse) ProtoMessage() {}

func (x *UploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_normal_upload_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadResponse.ProtoReflect.Descriptor instead.
func (*UploadResponse) Descriptor() ([]byte, []int) {
	return file_normal_upload_proto_rawDescGZIP(), []int{1}
}

func (x *UploadResponse) GetBaseResponse() *generate.BaseResponse {
	if x != nil {
		return x.BaseResponse
	}
	return nil
}

func (x *UploadResponse) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *UploadResponse) GetBucketId() string {
	if x != nil {
		return x.BucketId
	}
	return ""
}

func (x *UploadResponse) GetPathId() string {
	if x != nil {
		return x.PathId
	}
	return ""
}

func (x *UploadResponse) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *UploadResponse) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *UploadResponse) GetEtag() string {
	if x != nil && x.Etag != nil {
		return *x.Etag
	}
	return ""
}

func (x *UploadResponse) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *UploadResponse) GetIsCache() bool {
	if x != nil {
		return x.IsCache
	}
	return false
}

func (x *UploadResponse) GetUploadedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UploadedAt
	}
	return nil
}

func (x *UploadResponse) GetCacheVerifyDeadlineAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CacheVerifyDeadlineAt
	}
	return nil
}

func (x *UploadResponse) GetObjectKey() string {
	if x != nil && x.ObjectKey != nil {
		return *x.ObjectKey
	}
	return ""
}

type CacheVerifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheVerifyRequest) Reset() {
	*x = CacheVerifyRequest{}
	mi := &file_normal_upload_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheVerifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheVerifyRequest) ProtoMessage() {}

func (x *CacheVerifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_normal_upload_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheVerifyRequest.ProtoReflect.Descriptor instead.
func (*CacheVerifyRequest) Descriptor() ([]byte, []int) {
	return file_normal_upload_proto_rawDescGZIP(), []int{2}
}

func (x *CacheVerifyRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

type CacheVerifyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseResponse  *generate.BaseResponse `protobuf:"bytes,1,opt,name=base_response,json=baseResponse,proto3" json:"base_response,omitempty"`
	FileId        string                 `protobuf:"bytes,2,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	IsCache       bool                   `protobuf:"varint,3,opt,name=is_cache,json=isCache,proto3" json:"is_cache,omitempty"`
	CacheVerifyAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=cache_verify_at,json=cacheVerifyAt,proto3" json:"cache_verify_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheVerifyResponse) Reset() {
	*x = CacheVerifyResponse{}
	mi := &file_normal_upload_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheVerifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheVerifyResponse) ProtoMessage() {}

func (x *CacheVerifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_normal_upload_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheVerifyResponse.ProtoReflect.Descriptor instead.
func (*CacheVerifyResponse) Descriptor() ([]byte, []int) {
	return file_normal_upload_proto_rawDescGZIP(), []int{3}
}

func (x *CacheVerifyResponse) GetBaseResponse() *generate.BaseResponse {
	if x != nil {
		return x.BaseResponse
	}
	return nil
}

func (x *CacheVerifyResponse) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *CacheVerifyResponse) GetIsCache() bool {
	if x != nil {
		return x.IsCache
	}
	return false
}

func (x *CacheVerifyResponse) GetCacheVerifyAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CacheVerifyAt
	}
	return nil
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_normal_upload_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_normal_upload_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_normal_upload_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseResponse  *generate.BaseResponse `protobuf:"bytes,1,opt,name=base_response,json=baseResponse,proto3" json:"base_response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_normal_upload_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_normal_upload_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_normal_upload_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteResponse) GetBaseResponse() *generate.BaseResponse {
	if x != nil {
		return x.BaseResponse
	}
	return nil
}

var File_normal_upload_proto protoreflect.FileDescriptor

const file_normal_upload_proto_rawDesc = "" +
	"\n" +
	"\x13normal_upload.proto\x12\x05proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x0flink/base.proto\"\xa3\x01\n" +
	"\rUploadRequest\x12\x1b\n" +
	"\tbucket_id\x18\x01 \x01(\tR\bbucketId\x12\x17\n" +
	"\apath_id\x18\x02 \x01(\tR\x06pathId\x12%\n" +
	"\x0econtent_base64\x18\x03 \x01(\tR\rcontentBase64\x12%\n" +
	"\vdescription\x18\x04 \x01(\tH\x00R\vdescription\x88\x01\x01B\x0e\n" +
	"\f_description\"\x8b\x04\n" +
	"\x0eUploadResponse\x128\n" +
	"\rbase_response\x18\x01 \x01(\v2\x13.xBase.BaseResponseR\fbaseResponse\x12\x17\n" +
	"\afile_id\x18\x02 \x01(\tR\x06fileId\x12\x1b\n" +
	"\tbucket_id\x18\x03 \x01(\tR\bbucketId\x12\x17\n" +
	"\apath_id\x18\x04 \x01(\tR\x06pathId\x12\x1b\n" +
	"\tfile_name\x18\x05 \x01(\tR\bfileName\x12\x12\n" +
	"\x04size\x18\x06 \x01(\x03R\x04size\x12\x17\n" +
	"\x04etag\x18\a \x01(\tH\x00R\x04etag\x88\x01\x01\x12\x1b\n" +
	"\tmime_type\x18\b \x01(\tR\bmimeType\x12\x19\n" +
	"\bis_cache\x18\t \x01(\bR\aisCache\x12;\n" +
	"\vuploaded_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"uploadedAt\x12X\n" +
	"\x18cache_verify_deadline_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampH\x01R\x15cacheVerifyDeadlineAt\x88\x01\x01\x12\"\n" +
	"\n" +
	"object_key\x18\f \x01(\tH\x02R\tobjectKey\x88\x01\x01B\a\n" +
	"\x05_etagB\x1b\n" +
	"\x19_cache_verify_deadline_atB\r\n" +
	"\v_object_key\"-\n" +
	"\x12CacheVerifyRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\"\xc7\x01\n" +
	"\x13CacheVerifyResponse\x128\n" +
	"\rbase_response\x18\x01 \x01(\v2\x13.xBase.BaseResponseR\fbaseResponse\x12\x17\n" +
	"\afile_id\x18\x02 \x01(\tR\x06fileId\x12\x19\n" +
	"\bis_cache\x18\x03 \x01(\bR\aisCache\x12B\n" +
	"\x0fcache_verify_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\rcacheVerifyAt\"(\n" +
	"\rDeleteRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\"J\n" +
	"\x0eDeleteResponse\x128\n" +
	"\rbase_response\x18\x01 \x01(\v2\x13.xBase.BaseResponseR\fbaseResponse2\xc9\x01\n" +
	"\x13NormalUploadService\x125\n" +
	"\x06Upload\x12\x14.proto.UploadRequest\x1a\x15.proto.UploadResponse\x12D\n" +
	"\vCacheVerify\x12\x19.proto.CacheVerifyRequest\x1a\x1a.proto.CacheVerifyResponse\x125\n" +
	"\x06Delete\x12\x14.proto.DeleteRequest\x1a\x15.proto.DeleteResponseBAZ?github.com/phalanx-labs/beacon-bucket-sdk/internal/api;bGrpcApib\x06proto3"

var (
	file_normal_upload_proto_rawDescOnce sync.Once
	file_normal_upload_proto_rawDescData []byte
)

func file_normal_upload_proto_rawDescGZIP() []byte {
	file_normal_upload_proto_rawDescOnce.Do(func() {
		file_normal_upload_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_normal_upload_proto_rawDesc), len(file_normal_upload_proto_rawDesc)))
	})
	return file_normal_upload_proto_rawDescData
}

var file_normal_upload_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_normal_upload_proto_goTypes = []any{
	(*UploadRequest)(nil),         // 0: proto.UploadRequest
	(*UploadResponse)(nil),        // 1: proto.UploadResponse
	(*CacheVerifyRequest)(nil),    // 2: proto.CacheVerifyRequest
	(*CacheVerifyResponse)(nil),   // 3: proto.CacheVerifyResponse
	(*DeleteRequest)(nil),         // 4: proto.DeleteRequest
	(*DeleteResponse)(nil),        // 5: proto.DeleteResponse
	(*generate.BaseResponse)(nil), // 6: xBase.BaseResponse
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_normal_upload_proto_depIdxs = []int32{
	6, // 0: proto.UploadResponse.base_response:type_name -> xBase.BaseResponse
	7, // 1: proto.UploadResponse.uploaded_at:type_name -> google.protobuf.Timestamp
	7, // 2: proto.UploadResponse.cache_verify_deadline_at:type_name -> google.protobuf.Timestamp
	6, // 3: proto.CacheVerifyResponse.base_response:type_name -> xBase.BaseResponse
	7, // 4: proto.CacheVerifyResponse.cache_verify_at:type_name -> google.protobuf.Timestamp
	6, // 5: proto.DeleteResponse.base_response:type_name -> xBase.BaseResponse
	0, // 6: proto.NormalUploadService.Upload:input_type -> proto.UploadRequest
	2, // 7: proto.NormalUploadService.CacheVerify:input_type -> proto.CacheVerifyRequest
	4, // 8: proto.NormalUploadService.Delete:input_type -> proto.DeleteRequest
	1, // 9: proto.NormalUploadService.Upload:output_type -> proto.UploadResponse
	3, // 10: proto.NormalUploadService.CacheVerify:output_type -> proto.CacheVerifyResponse
	5, // 11: proto.NormalUploadService.Delete:output_type -> proto.DeleteResponse
	9, // [9:12] is the sub-list for method output_type
	6, // [6:9] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_normal_upload_proto_init() }
func file_normal_upload_proto_init() {
	if File_normal_upload_proto != nil {
		return
	}
	file_normal_upload_proto_msgTypes[0].OneofWrappers = []any{}
	file_normal_upload_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_normal_upload_proto_rawDesc), len(file_normal_upload_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_normal_upload_proto_goTypes,
		DependencyIndexes: file_normal_upload_proto_depIdxs,
		MessageInfos:      file_normal_upload_proto_msgTypes,
	}.Build()
	File_normal_upload_proto = out.File
	file_normal_upload_proto_goTypes = nil
	file_normal_upload_proto_depIdxs = nil
}
